"""Real Blender -> managed GLB -> built Three.js -> Chrome regression smoke.

All images/scenes are synthetic integration fixtures, not reference-fidelity
benchmarks. No mock workers, private assets, external URLs or production jobs.
"""
from __future__ import annotations

import argparse
import io
import json
from pathlib import Path
import subprocess
import os

from PIL import Image

from server3d.builder import REPO, build_files, sha, write_build
from server3d.jobs import Store
from server3d.scene_schema import ScenePlan, validate_analysis
from server3d.glb_validation import validate_glb
from server3d.tests.test_embedded_textures import fixture, pack


def run(output: Path):
    output.mkdir(parents=True, exist_ok=False)
    store = Store(output / "store")
    base = store.components.generate({"template": "cargo_crate", "detail": 1}, "base")
    changed = store.components.generate({"template": "cargo_crate", "detail": 1,
        "deformation_handles": [{"anchor": [.4, .7, .3], "offset": [.03, .04, 0.],
                                 "radius": .6, "strength": 1.}]}, "deformed")
    if changed["asset_id"] == base["asset_id"]:
        raise RuntimeError("Real Blender deformation did not alter the output asset")
    image = io.BytesIO()
    Image.new("RGB", (640, 480), "#ededed").save(image, "PNG")
    source = store.upload(image.getvalue())
    analysis = validate_analysis({"source_sha256": source["sha256"], "scene_box": [0, 0, 640, 480],
        "regions": [{"id": "crate", "label": "Synthetic crate", "box": [0, 0, 640, 480],
                     "confidence": 1., "evidence": "Integration fixture only"}],
        "assumptions": [], "change_reason": "Synthetic integration test"}, source).model_dump()
    # This additional fixture exercises the REAL GLTFLoader texture plugin;
    # it is not claimed to have been generated by Blender.
    texture_bytes = pack(*fixture())
    texture_id = sha(texture_bytes)
    textured = {"record": {"asset_id": texture_id, "origin": "synthetic_integration_fixture",
                "geometry": validate_glb(texture_bytes, texture_profile="embedded-png-v1")}, "bytes": texture_bytes}
    cases = []
    for mode in ("legacy", "reference"):
        for quality in ("standard", "showcase"):
            cases.append((f"blender-{mode}-{quality}", changed["asset_id"], mode, quality))
    cases.append(("textured-reference", texture_id, "reference", "standard"))
    report = {"kind": "synthetic-real-render-integration-v1", "source_is_user_reference": False,
              "blender": base["blender"], "base_asset": base["asset_id"], "deformed_asset": changed["asset_id"],
              "cases": [], "workflow_complete": False}
    for name, identity, mode, quality in cases:
        plan = ScenePlan.model_validate({"title": name, "appearance_mode": mode, "render_quality": quality,
            "camera": {"position": [6., 5., 8.], "target": [0., 1., 0.], "vertical_span": 5.},
            "materials": [{"id": "wood", "color": "#75513c"}],
            "objects": [{"id": "crate", "label": "Synthetic crate", "kind": "asset", "asset_id": identity,
                         "region_ids": ["crate"], "position": [0., 0., 0.], "dimensions": [2., 2., 2.],
                         "material_id": "wood", "movement": {"bounds": [-2., -2., 2., 2.], "amplitude": .1},
                         "inferred_surfaces": "Synthetic integration fixture; not reconstruction evidence"}],
            "assumptions": ["Synthetic integration fixture"]}).model_dump()
        if identity == texture_id:
            components = {identity: textured}
        else:
            with store.transaction() as db:
                components = store.components.build_assets(plan, db)
        build_id, files, _ = build_files(plan, source, analysis, "integration", name, components)
        directory = output / "builds" / build_id
        write_build(directory, files)
        capture_dir = output / name
        result = subprocess.run([os.getenv("CANVASLAB3D_NODE", "node"), str(REPO / "scripts3d/capture.mjs"),
                                 str(directory), str(capture_dir)], capture_output=True, text=True, timeout=150)
        (output / f"{name}.log").write_text(result.stdout + "\n" + result.stderr, encoding="utf-8")
        if result.returncode:
            raise RuntimeError(f"Real capture failed: {name}: {result.stderr[-2000:]}")
        observation = json.loads((capture_dir / "observation.json").read_text())
        failed = [test for test in observation["tests"] if not test["passed"]]
        row = {"case": name, "build_id": build_id, "browser": observation["browser_version"],
               "passed_checks": len(observation["tests"]) - len(failed),
               "total_checks": len(observation["tests"]), "failed": failed, "errors": observation["errors"]}
        report["cases"].append(row)
        (output / "integration-report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
        print(json.dumps(row), flush=True)
        if failed or observation["errors"]:
            raise RuntimeError(f"Real browser checks failed: {name}")
    return report


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path, help="Fresh evidence directory; never overwrites existing output")
    run(parser.parse_args().output.resolve())
