"""Real Blender -> managed GLB -> built Three.js -> Chrome regression smoke.

All images/scenes are synthetic integration fixtures, not reference-fidelity
benchmarks. No mock workers, private assets, external URLs or production jobs.
"""
from __future__ import annotations

import argparse
import io
import json
from pathlib import Path
import subprocess
import os

from PIL import Image, ImageDraw

from server3d.builder import REPO, build_files, sha, write_build
from server3d.jobs import Store
from server3d.scene_schema import ScenePlan, validate_analysis
from server3d.glb_validation import validate_glb
from server3d.tests.test_embedded_textures import fixture, pack


def run(output: Path, group: str = "all"):
    if group not in {"all", "standard", "showcase", "projection"}:
        raise ValueError("Unknown integration group")
    output.mkdir(parents=True, exist_ok=False)
    store = Store(output / "store")
    base = store.components.generate({"template": "cargo_crate", "detail": 1}, "base")
    changed = store.components.generate({"template": "cargo_crate", "detail": 1,
        "deformation_handles": [{"anchor": [.4, .7, .3], "offset": [.03, .04, 0.],
                                 "radius": .6, "strength": 1.}]}, "deformed")
    if changed["asset_id"] == base["asset_id"]:
        raise RuntimeError("Real Blender deformation did not alter the output asset")
    image = io.BytesIO()
    original = Image.new("RGB", (640, 480), "#cabbaa")
    draw = ImageDraw.Draw(original)
    for x in range(0, 640, 16):
        draw.rectangle((x, 0, x+7, 479), fill="#1d659a" if x % 32 else "#db6245")
    for y in range(0, 480, 40):
        draw.rectangle((0, y, 639, y+5), fill="#f2d992")
    original.save(image, "PNG")
    (output / "synthetic-source.png").write_bytes(image.getvalue())
    source = store.upload(image.getvalue())
    analysis = validate_analysis({"source_sha256": source["sha256"], "scene_box": [0, 0, 640, 480],
        "regions": [{"id": "crate", "label": "Synthetic crate", "box": [0, 0, 640, 480],
                     "confidence": 1., "evidence": "Integration fixture only",
                     "visible_polygons": [[[0, 0], [640, 0], [640, 480], [0, 480]]]}],
        "assumptions": [], "change_reason": "Synthetic integration test"}, source).model_dump()
    # This additional fixture exercises the REAL GLTFLoader texture plugin;
    # it is not claimed to have been generated by Blender.
    texture_bytes = pack(*fixture())
    texture_id = sha(texture_bytes)
    textured = {"record": {"asset_id": texture_id, "origin": "synthetic_integration_fixture",
                "geometry": validate_glb(texture_bytes, texture_profile="embedded-png-v1")}, "bytes": texture_bytes}
    cases = []
    for mode in ("legacy", "reference"):
        for quality in ("standard", "showcase"):
            cases.append((f"blender-{mode}-{quality}", changed["asset_id"], mode, quality))
    cases.append(("textured-reference", texture_id, "reference", "standard"))
    cases.append(("projected-reference", texture_id, "reference", "standard"))
    if group != "all":
        cases = [case for case in cases if
                 (group == "projection" and case[0] in {"textured-reference", "projected-reference"}) or
                 (group in {"standard", "showcase"} and case[0].startswith("blender-") and case[3] == group)]
    report = {"group": group, "capture_timeout_seconds": 600, "kind": "synthetic-real-render-integration-v1", "source_is_user_reference": False,
              "blender": base["blender"], "base_asset": base["asset_id"], "deformed_asset": changed["asset_id"],
              "cases": [], "workflow_complete": False}
    for name, identity, mode, quality in cases:
        plan = ScenePlan.model_validate({"title": name, "appearance_mode": mode, "render_quality": quality,
            "camera": {"position": [6., 5., 8.], "target": [0., 1., 0.], "vertical_span": 5.},
            "materials": [{"id": "wood", "color": "#75513c"}],
            "objects": [{"id": "crate", "label": "Synthetic crate", "kind": "asset", "asset_id": identity,
                         "region_ids": ["crate"], "position": [0., 0., 0.], "dimensions": [2., 2., 2.],
                         "material_id": "wood", "movement": {"bounds": [-2., -2., 2., 2.], "amplitude": .1},
                         "inferred_surfaces": "Synthetic integration fixture; not reconstruction evidence"}],
            "assumptions": ["Synthetic integration fixture"]}).model_dump()
        if name == "projected-reference":
            plan.update(reference_projection={"object_ids": ["crate"]},
                        reference_lighting={"tone_mapping": "none", "exposure": 1.})
            plan = ScenePlan.model_validate(plan).model_dump()
        if identity == texture_id:
            components = {identity: textured}
        else:
            with store.transaction() as db:
                components = store.components.build_assets(plan, db)
        build_id, files, _ = build_files(plan, source, analysis, "integration", name, components,
            **({"source_bytes": image.getvalue()} if plan.get("reference_projection") else {}))
        directory = output / "builds" / build_id
        write_build(directory, files)
        capture_dir = output / name
        result = subprocess.run([os.getenv("CANVASLAB3D_NODE", "node"), str(REPO / "scripts3d/capture.mjs"),
                                 str(directory), str(capture_dir)], capture_output=True, text=True, timeout=600)
        (output / f"{name}.log").write_text(result.stdout + "\n" + result.stderr, encoding="utf-8")
        if result.returncode:
            raise RuntimeError(f"Real capture failed: {name}: {result.stderr[-2000:]}")
        observation = json.loads((capture_dir / "observation.json").read_text())
        failed = [test for test in observation["tests"] if not test["passed"]]
        row = {"case": name, "build_id": build_id, "browser": observation["browser_version"],
               "passed_checks": len(observation["tests"]) - len(failed),
               "total_checks": len(observation["tests"]), "failed": failed, "errors": observation["errors"]}
        if name == "projected-reference":
            import numpy as np
            actual = np.asarray(Image.open(capture_dir / "reference.png").convert("RGB"), dtype=float)
            expected = np.asarray(original, dtype=float)
            labels = Image.open(capture_dir / "id.png").convert("RGB").getchannel("B")
            from PIL import ImageFilter
            reliable = labels.point(lambda v: 255 if v == 1 else 0).filter(ImageFilter.MinFilter(5))
            selected = np.asarray(reliable) > 0
            errors = np.abs(actual - expected).mean(axis=2)[selected]
            if not len(errors):
                raise RuntimeError("Synthetic projection has no measured visible pixels")
            row["source_projection_pixel_test"] = {"synthetic_visible_pixels": int(selected.sum()),
                "mean_abs_rgb_code_error": float(errors.mean()),
                "within_two_code_values_fraction": float((errors < 2).mean()),
                "not_a_reconstruction_fidelity_score": True}
            row["total_checks"] += 1
            if (errors < 2).mean() < .85:
                failed.append({"name": "synthetic_source_pixels_preserved", "passed": False})
            else:
                row["passed_checks"] += 1
        report["cases"].append(row)
        (output / "integration-report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
        print(json.dumps(row), flush=True)
        if failed or observation["errors"]:
            raise RuntimeError(f"Real browser checks failed: {name}")
    return report


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path, help="Fresh evidence directory; never overwrites existing output")
    parser.add_argument("--group", choices=("all", "standard", "showcase", "projection"), default="all")
    args = parser.parse_args()
    run(args.output.resolve(), args.group)
